let news = [
  {
    title: "new fashion 2023",
    description: "super 2023 model",
    pubDate: "6/12/2023",
    auth: "Adriana lima",
    category: "Fashion",
  },
  {
    title: " news sport ",
    description: dulmaa,
    pubDate: "6/12/2023",
    auth: "Ronaldo",
    category: "sport",
  },
  {
    title: "M5-started",
    description: 15,
    pubDate: "6/12/2023",
    auth: "Kairi",
    category: "E-esport",
  },
  {
    title: "M5-started",
    description: 15,
    pubDate: "6/12/2023",
    auth: "bennyqt",
    category: "E-esport",
  },
  {
    title: "M5-started",
    description: 15,
    pubDate: "6/12/2023",
    auth: "Sanford",
    category: "E-esport",
  },
  {
    title: "new fashion",
    description: 15,
    pubDate: "6/12/2023",
    auth: "Adriana lima",
    category: "Fashion",
  },
  {
    title: "new fashion 2023",
    description: 15,
    pubDate: "6/12/2023",
    auth: "Adriana lima",
    category: "Fashion",
  },
  {
    title: "new fashion 2023",
    description: 15,
    pubDate: "6/12/2023",
    auth: "Adriana lima",
    category: "Fashion",
  },

  {
    title: "new fashion 2023",
    description: 15,
    pubDate: "6/12/2023",
    auth: "Adriana lima",
    category: "Fashion",
  },
  {
    title: "new fashion 2023",
    description: 15,
    pubDate: "6/12/2023",
    auth: "Adriana lima",
    category: "Fashion",
  },
];
